server:
  port: 8888

spring:
  datasource:
    username: vgxlzkqppiyxeq
    password: 10c50c312a01aca3ffeba34744ac27b1c7fe8388f35841162dd8fd9dac43aa9a
    url: jdbc:postgresql://ec2-34-230-153-41.compute-1.amazonaws.com:5432/dekobi0iraf2d3
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true